POST http://193.196.54.172:8000/api/events
Content-Type: application/json

{
  "name": "Fresh Try ResponseEntities",
  "description": "Bla Bla",
  "room": "0.108",
  "exchangeDayId": 6,
  "organizerId": 3,
  "startTime": "13:00:00",
  "endTime": "14:00:00"

}
###
POST http://193.196.54.172:8000/api/users
Content-Type: application/json

{
  "username": "mperreks",
  "surname": "Maximilian",
  "lastname": "Peresunchak",
  "role": "ADMIN"
}
###
POST http://193.196.54.172:8000/api/exchange-days
Content-Type: application/json

{
  "date": "2024-11-25",
  "name": "Spring Boot Exchange Day",
  "location": "Berlin",
  "description": "A day dedicated to learning Spring Boot with multiple sessions."
}
###
GET http://193.196.54.172:8000/api/exchange-days
###
GET http://193.196.54.172:8000/api/events
###
GET http://193.196.54.172:8000/api/users?username=mperreks