POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Fresh Try ResponseEntities",
  "description": "Bla Bla",
  "room": "0.108",
  "exchangeDayId": 1,
  "organizerId": 2,
  "startTime": "13:00:00",
  "endTime": "14:00:00"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "maxTwo",
  "firstname": "Maximilian",
  "lastname": "Peresunchak",
  "role": "ADMIN"
}
###
POST http://localhost:8080/api/exchange-days
Content-Type: application/json

{
  "date": "2025-12-30",
  "name": "Fresh",
  "location": "Frankfurt",
  "description": "A day dedicated to learning Spring Boot with multiple sessions."
}
###
GET http://localhost:8080/api/exchange-days
###
GET http://localhost:8080/api/events
###
GET http://localhost:8080/api/users/1/feedback
###
GET http://localhost:8080/api/feedback
###
GET http://localhost:8080/api/users/search?username=maxTwo

###
POST http://localhost:8080/api/feedback
Content-Type: application/json

{
  "overallScore": 5,
  "organisationalScore": 2,
  "relevanceScore": 3,
  "understandabilityScore": 3,
  "contentDepthScore": 4,
  "practicalityScore": 2,
  "reasonabilityScore": 1,
  "competencyScore": 3,
  "presentabilityScore": 2,
  "interactivityScore": 5,
  "timeManagementScore": 2,
  "participationScore": 1,
  "atmosphereScore": 5,
  "communicationScore": 3,
  "networkingScore": 2,
  "comfortabilityScore": 3,
  "equipmentScore": 1,
  "enjoymentComment": "I liked this workshop, because you mentioned some new things that I didnt know beforehand.",
  "improvementComment": "You should try to involve the people inside the workshop and maybe set up questions before, so that you have anchors throughout.",
  "requestComment": "I want to learn more about Java reflection and maybe some more things on Java 23 features.",
  "personalImprovementComment": "I learned that this workshop really prepares you to work with docker and cubernetes.",
  "isEventRecommended": true,
  "recommendationComment": "I would definitely recommend this workshop to anyone that wants to work in web deployment.",
  "similarEventParticipationScore": 5,
  "anonymousFeedback": true,
  "eventId": 11
}

###
DELETE http://localhost:8080/api/feedback/3

###
GET http://localhost:8080/api/events/11/feedback

###
POST http://localhost:8080/api/events/11/attendance
Content-Type: application/json

{
  "token": "dwh054q3d2",
  "userId": 1
}

###
POST http://localhost:8080/api/users/1/eventRegistration?eventId=11

###
DELETE http://localhost:8080/api/users/1/eventRegistration?eventId=11

###
GET http://localhost:8080/api/events/10/qr-code

###
GET http://localhost:8080/api/events/5/qr-code
###
GET http://localhost:8080/api/users
###
GET http://localhost:8080/api/events/5
###
POST http://localhost:8080/api/forumposts
Content-Type: application/json

{
  "forumThreadId": 1,
  "content": "I am really looking forward to this event. I hope it will be as good as the last one."
}
###
POST http://localhost:8080/api/forumthreads
Content-Type: application/json

{
  "eventId": 1,
  "title": "Event Discussion",
  "description": "Discuss everything about the event here."
}
###
GET http://localhost:8080/api/events/1/forumposts
###
GET http://localhost:8080/api/forumthreads/1

