GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/events
###

POST http://localhost:8080/api/exchange-days
Content-Type: application/json

{
    "date": "2024-11-15",
    "name": "Spring Boot Exchange Day",
    "location": "Berlin",
    "description": "A day dedicated to learning Spring Boot with multiple sessions."
}

###
POST http://localhost:8080/api/events
Content-Type: application/json

{
    "name": "Spring Boot Fundamentals",
    "location": "Room A",
    "startTime": "13:00",
    "endTime": "14:00",
    "organizer": {"id": 1},
    "exchangeDay": {
        "id": 1
    }
}

###
GET http://localhost:8080/api/exchange-days/1

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "mperreks",
  "surname": "Maximilian",
  "lastname": "Peresunchak",
  "role": "ADMIN"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "mifi",
  "surname": "Maximilian",
  "lastname": "Rau",
  "role": "ADMIN"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "crazyday",
  "surname": "Deniz",
  "lastname": "Altunkapan",
  "role": "USER"
}

###
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "username": "mperreks",
  "surname": "Maximilian",
  "lastname": "Peresunchak",
  "role": "ADMIN"
}

###
PUT http://localhost:8080/api/users/2
Content-Type: application/json

{
  "username": "mifi",
  "surname": "Maximilian",
  "lastname": "Rau",
  "role": "ADMIN"
}

###
PUT http://localhost:8080/api/users/3
Content-Type: application/json

{
  "username": "crazyday",
  "surname": "Deniz",
  "lastname": "Altunkapan",
  "role": "ADMIN"
}

###
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Einführung in Git",
  "startTime": "10:00:00",
  "endTime": "12:00:00",
  "description": "Eine kleine Einführung in Git",
  "room": "0.108",
  "organizer": {
    "id": 2
  },
  "registeredUsers": [
    {
      "id": 1
    }
  ],
  "exchangeDay": {
    "id": 1,
    "date": "2023-12-01",
    "name": "Austauschtag Dezember",
    "location": "Berlin",
    "description": "Ein Tag für den Austausch von Wissen und Ideen."
  }
}

###
POST http://localhost:8080/api/exchange-days
Content-Type: application/json

{
  "date": "2024-12-10",
  "name": "GitHub Exchange Day 2",
  "location": "Stuttgart",
  "description": "A day dedicated to learning GitHub with multiple sessions."
}

###
POST http://localhost:8080/api/exchange-days
Content-Type: application/json

{
  "date": "2025-12-10",
  "name": "Itestra Exchange Day 2",
  "location": "München",
  "description": "A day dedicated to learning GitHub with Itestra!"
}

###
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "GitHub Fundamentals",
  "location": "Room A",
  "startTime": "10:00:00",
  "description": "GitHub & Git blabla",
  "endTime": "11:00:00",
  "organizer": {"id": 1},
  "exchangeDay": {
    "id": 1
  }
}
###
POST http://localhost:8080/api/events
Content-Type: application/json

{
"name": "GitHub Fundamentals",
"location": "Room A",
"startTime": "10:00:00",
"description": "GitHub & Git blabla 2",
"endTime": "11:00:00",
  "organizer": {"id": 1},
"exchangeDay": {
"id": 2
}
}
